  ./configure --build=i586-redhat-linux-gnu --host=i586-redhat-linux-gnu \
        --target=i586-redhat-linux-gnu \
        --program-prefix= \
        --prefix=/usr \
        --exec-prefix=/usr \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --includedir=/usr/include \
        --libdir=/usr/lib \
        --libexecdir=/usr/libexec \
        --localstatedir=/var \
        --sharedstatedir=/var/lib \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --with-ufdb-user=ufdb \
        --prefix=/usr \
        --with-ufdb-bindir=/usr/sbin \
        --with-ufdb-piddir=/var/run/ufdbguard \
        --with-ufdb-mandir=/usr/share/man \
        --with-ufdb-images_dir=/var/ufdbguard/images \
        --with-ufdb-logdir=/var/ufdbguard/logs \
        --with-ufdb-samplesdir=/var/ufdbguard/samples \
        --with-ufdb-config=/etc/ufdbguard \
        --with-ufdb-dbhome=/var/ufdbguard/blacklists 

